version: "3.7"
services:
  jupyterlab:
    build: .
    user: root
    # Image name.
    image: ml_bots_base
    # Contaniner name
    container_name: ml_bots
    env_file:
      - .env
    ports:
      - "8888:8888" # Port for jupyterlab.
      - "8501:8501" # Port for streamlit.
      - "5000:5000" # Port for mlflow.
    volumes:
      - ~/ml_bots:/home/$NB_USER/work
    working_dir: /home/$NB_USER/work
    networks:
      - local_network
    command: start.sh jupyter lab --NotebookApp.token=''


networks:
  local_network:
    external: true